* Publishing a HyWiki

A HyWiki can be exported to HTML for publishing to the web via Org
mode's publish a project feature.  {C-h h h p} or {M-x
hywiki-publish-to-html <RET>} publishes any changed files in the HyWiki.
Give that command a prefix argument to force republishing of all HyWiki
pages.

The full set of HyWiki-specific Org publish properties are set in the
variable 'hywiki-org-publish-project-alist'.  When the HyWiki code is
loaded into Emacs, it automatically integrates these properties with
Org's publishing framework, so when in a HyWiki page, you can use
Org's standard {C-c C-e P p} current project publish command if you
prefer.

There are a few publishing settings you can customize prior to loading
Hyperbole's HyWiki code.

HyWiki html files are saved in: (hywiki-org-get-publish-property
:publishing-directory).  Customize this directory with: {M-x
customize-variable <RET> hywiki-org-publishing-directory <RET>}

HyWiki html files are generated by the function given by:
(hywiki-org-get-publish-property :publishing-function).  Customize the
value of this function if necessary with: {M-x customize-variable
<RET> hywiki-org-publishing-function <RET>}
